./writeRubricTransformz.sh ISO ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh ISO-1 ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh DIF ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh DIF-10 ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh FGDC ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh ECHO ACDD ACDD_highlyRecommended ACDD_recommended ACDD_suggested
./writeRubricTransformz.sh ISO CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh ISO-1 CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh DIF CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh DIF-10 CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh FGDC CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh ECHO CSW CSWCoreQueryables CSWCoreReturnables CSWAdditionalQueryables
./writeRubricTransformz.sh ISO DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh ISO-1 DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh DIF DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh DIF-10 DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh FGDC DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh ECHO DCITE DataCite3.1Mandatory DataCite3.1Recommended DataCite3.1Optional
./writeRubricTransformz.sh ISO-1 UMM-C UMM-C_Required UMM-C_HighlyRecommended UMM-C_Recommended
./writeRubricTransformz.sh DIF UMM-C UMM-C_Required UMM-C_HighlyRecommended UMM-C_Recommended
./writeRubricTransformz.sh DIF-10 UMM-C UMM-C_Required UMM-C_HighlyRecommended UMM-C_Recommended
./writeRubricTransformz.sh FGDC UMM-C UMM-C_Required UMM-C_HighlyRecommended UMM-C_Recommended
./writeRubricTransformz.sh ECHO UMM-C UMM-C_Required UMM-C_HighlyRecommended UMM-C_Recommended
